services:
  ollama:
    image: ollama/ollama:latest
    container_name: webc_ollama
    restart: unless-stopped
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - internal_net

  scraper:
    build: .
    container_name: webc_scraper
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - TZ=${TIMEZONE}
      - CAL_ID=${CALENDAR_ID}
    volumes:
      - shared_data:/output
    networks:
      - internal_net

  web:
    image: caddy:alpine
    container_name: webc_caddy
    restart: unless-stopped
    ports:
      - "1860:80"
    environment:
      - CAL_ID=${CALENDAR_ID}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./index.html:/srv/index.html
      - shared_data:/srv/files
    networks:
      - internal_net

volumes:
  ollama_storage:
  shared_data:

networks:
  internal_net:
