services:
  web:
    image: caddy:alpine
    container_name: webc_caddy
    restart: unless-stopped
    ports:
      - "1860:80"
    environment:
      - CAL_ID=${CALENDAR_ID}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/srv/files:ro
    networks:
      - web_gateway

networks:
  web_gateway:
    external: true